package com.caucraft.shadowmap.client.gui;

import com.caucraft.shadowmap.client.ShadowMap;
import net.minecraft.util.Identifier;

public enum Icons {
    ADD_GROUP,
    ADD_WAYPOINT,
    ALPHA_ASCEND,
    ALPHA_DESCEND,
    ARROW_LEFT,
    ARROW_RIGHT,
    AUTORESIZE_OFF,
    AUTORESIZE_ON,
    BLINK,
    CIRCLE,
    COPY,
    DELETE_GROUP_AND_CHILDREN,
    DELETE_GROUP_NOT_CHILDREN,
    DESKTOP,
    DOWNLOAD,
    DRAW_COLLAPSE_FILTER,
    DRAW_COLLAPSE_NONE,
    DRAW_COLLAPSE_POINT,
    DRAW_COLLAPSE_POINT_FILTER,
    DRAW_EXPAND_FILTER,
    DRAW_EXPAND_NONE,
    DRAW_EXPAND_POINT,
    DRAW_EXPAND_POINT_FILTER,
    EDIT_OFF,
    EDIT_ON,
    EXPAND_FILTER_OFF,
    EXPAND_FILTER_ON,
    EXPAND_OFF,
    EXPAND_ON,
    EXPORT,
    FILE,
    FILTER_OFF,
    FILTER_ON,
    FLOPPY,
    FOLDER,
    GEAR_THICK,
    GEAR_THIN,
    GRAYSS_BLOCK,
    GRID_OFF,
    GRID_ON,
    HIGHLIGHTER_OFF,
    HIGHLIGHTER_ON,
    HOME,
    IMPORT,
    INFO_OFF,
    INFO_ON,
    LEAVE_FOLDER,
    LOCK_OFF,
    LOCK_ON,
    MINUS,
    NO_CIRCLE,
    OCTAGON,
    PLUS,
    SET_FOCUS,
    SHAPES,
    SQUARE,
    STOPWATCH_OFF,
    STOPWATCH_ON,
    TILE_BL,
    TILE_BR,
    TILE_TL,
    TILE_TR,
    TIME_ASCEND,
    TIME_DESCEND,
    TRASH,
    VISIBLE_FILTER_OFF,
    VISIBLE_FILTER_ON,
    VISIBLE_OFF,
    VISIBLE_ON,
    WAYPOINT_LIST,
    WAYPOINT_OFF,
    WAYPOINT_ON;

    public final Identifier id;

    Icons() {
        this.id = new Identifier(ShadowMap.MOD_ID, name().toLowerCase());
    }
}
